#
# _config.yml for www.freeloader.wtf
#

exclude: [ "CNAME", "README.md", "LICENSE.txt", "TODO.md", "tmp", "*.sh", "**/*_src*" ]
permalink: /news/:year-:month-:day/index.html
production_url: https://www.freeloader.wtf
title : Freeloader.WTF
gems:
  - jekyll-redirect-from
markdown: kramdown
redirect_from:
  json: false
theme: null

